<?php
declare(strict_types=1);
define('OC_CONSOLE', true);
require '/var/www/html/lib/base.php';
set_exception_handler(static function (Throwable $error): void { fwrite(STDERR, (string)$error . "\n"); exit(1); });

use OCA\ShareManager\Controller\ShareController;
use OCA\ShareManager\Service\ShareTreeService;
use OCP\Files\IRootFolder;
use OCP\IRequest;
use OCP\IUserManager;
use OCP\IUserSession;
use OCP\IGroupManager;
use OCP\Lock\ILockingProvider;
use OCP\Share\IManager;
use OCP\Share\IShare;

function check(bool $condition, string $message): void {
    if (!$condition) throw new RuntimeException($message);
    echo "PASS: $message\n";
}
$users = \OCP\Server::get(IUserManager::class);
$session = \OCP\Server::get(IUserSession::class);
$manager = \OCP\Server::get(IManager::class);
$groups = \OCP\Server::get(IGroupManager::class);
$files = \OCP\Server::get(IRootFolder::class);
$service = new ShareTreeService($manager, $files, $groups, $users);
$controller = new ShareController(\OCP\Server::get(IRequest::class), $manager, $session, $service, \OCP\Server::get(ILockingProvider::class));
$suffix = bin2hex(random_bytes(5));
$people = [];
$group = null;
try {
    foreach (range('A', 'G') as $letter) $people[$letter] = $users->createUser('sm_' . $letter . '_' . $suffix, bin2hex(random_bytes(24)));
    $uid = fn (string $letter) => $people[$letter]->getUID();
    $session->setUser($people['A']);
    $home = $files->getUserFolder($uid('A'));
    $root = $home->newFolder('Projekt');
    $sub1 = $root->newFolder('subordner');
    $sub2 = $root->newFolder('subordner2');
    $sub1->newFolder('Ohne direkte Freigabe');
    $otherRoot = $home->newFolder('Projekt-anders');
    $create = function (string $by, int $nodeId, int $type, ?string $recipient, int $permissions = 17) use ($people, $files, $manager, $session, $uid): IShare {
        $session->setUser($people[$by]);
        $folder = $files->getUserFolder($uid($by));
        $folder->getDirectoryListing();
        $node = $folder->getFirstNodeById($nodeId);
        if ($node === null) throw new RuntimeException('Reshare mount could not be resolved for ' . $by);
        $share = $manager->newShare()->setNode($node)->setShareType($type)->setSharedBy($uid($by))->setPermissions($permissions);
        if ($recipient !== null) $share->setSharedWith($recipient);
        return $manager->createShare($share);
    };
    $ab = $create('A', $root->getId(), 0, $uid('B'));
    $bc = $create('B', $root->getId(), 0, $uid('C'));
    $cd = $create('C', $sub1->getId(), 0, $uid('D'), 1);
    $ce = $create('C', $sub1->getId(), 0, $uid('E'), 1);
    $cf = $create('C', $sub2->getId(), 0, $uid('F'), 1);
    $ad = $create('A', $sub2->getId(), 0, $uid('D'), 1);
    $same = $create('A', $sub2->getId(), 0, $uid('B'));
    $outside = $create('A', $otherRoot->getId(), 0, $uid('D'), 1);
    $session->setUser($people['A']);
    $response = $controller->index();
    check($response->getStatus() === 200, 'Inventory succeeds: ' . json_encode($response->getStatus() === 200 ? [] : $response->getData()));
    $data = $response->getData();
    $tree = array_values(array_filter($data['trees'], fn ($tree) => $tree['id'] === $root->getId()))[0];
    check(count($tree['users']) === 5, 'A sees B, C, D, E and F across the tree');
    $nodeRows = array_column($tree['nodes'], null, 'id');
    check(count($tree['nodes']) === 4, 'Tree includes unshared intermediate folders');
    check($nodeRows[$sub1->getId()]['parentId'] === $root->getId(), 'Subfolder retains tree parent');
    check(isset($nodeRows[$sub1->getId()]['effectiveUsers'][$uid('B')]), 'Inherited access shown on subfolder');
    $allRows = array_merge(...array_column($tree['nodes'], 'shares'));
    $byId = array_column($allRows, null, 'id');
    check($byId[$bc->getFullId()]['foreign'] && !$byId[$bc->getFullId()]['belowTop'] && $byId[$bc->getFullId()]['deviation'], 'B to C is foreign and deviating even on top level');
    check($byId[$cd->getFullId()]['foreign'] && $byId[$cd->getFullId()]['belowTop'] && $byId[$cd->getFullId()]['deviation'], 'C to D matches all three filters');
    check(!$byId[$same->getFullId()]['foreign'] && $byId[$same->getFullId()]['belowTop'] && !$byId[$same->getFullId()]['deviation'], 'Equivalent B grant on subfolder is below top but not deviating');
    check(!isset($byId[$outside->getFullId()]), 'Sibling prefix is not mistaken for a descendant');
    $session->setUser($people['B']);
    check($controller->preview($root->getId(), $uid('D'))->getStatus() === 403, 'Recipient cannot plan owner-wide revocation');
    check($controller->destroy($cd->getFullId())->getStatus() === 403, 'Unrelated sharer cannot delete C grant');
    $session->setUser(null);
    check($controller->index()->getStatus() === 401 && $controller->preview($root->getId(), $uid('D'))->getStatus() === 401, 'Anonymous read and preview rejected');
    check($controller->revoke($root->getId(), $uid('D'), 'fake')->getStatus() === 401, 'Anonymous execution rejected');
    $session->setUser($people['A']);
    check($controller->preview($root->getId(), $uid('A'))->getStatus() === 422, 'Owner cannot revoke their own ownership');
    check($controller->preview($sub1->getId(), $uid('D'))->getStatus() === 403, 'Subtree cannot ignore grants inherited from root');
    $plan = $controller->preview($root->getId(), $uid('D'))->getData();
    check($plan['canExecute'] && count($plan['affected']) === 2, 'Preview includes grants to D from both A and C');
    $result = $controller->revoke($root->getId(), $uid('D'), $plan['fingerprint']);
    check($result->getStatus() === 200 && $result->getData()['remaining'] === [], 'D loses access throughout selected tree');
    check(!isset($manager->getAccessList($sub1, true, true)['users'][$uid('D')]), 'Real access list confirms D removal');
    check(isset($manager->getAccessList($sub1, true, true)['users'][$uid('E')]), 'E retains unrelated access');
    check(isset($manager->getAccessList($otherRoot, true, true)['users'][$uid('D')]), 'D retains access outside selected tree');
    $plan = $controller->preview($root->getId(), $uid('F'))->getData();
    $extra = $create('A', $sub2->getId(), 0, $uid('E'), 1);
    $session->setUser($people['A']);
    check($controller->revoke($root->getId(), $uid('F'), $plan['fingerprint'])->getStatus() === 409, 'Stale preview is rejected without deletion');
    check(isset($manager->getAccessList($sub2, true, true)['users'][$uid('F')]), 'Stale request preserved F share');
    $group = $groups->createGroup('sm_group_' . $suffix);
    $group->addUser($people['D']); $group->addUser($people['G']);
    $groupShare = $create('A', $sub1->getId(), 1, $group->getGID(), 1);
    $link = $create('A', $sub2->getId(), 3, null, 1);
    $session->setUser($people['A']);
    $blocked = $controller->preview($root->getId(), $uid('D'))->getData();
    check(!$blocked['canExecute'] && count($blocked['blockers']) === 2, 'Group and public link prevent false complete-revocation claim');
    check($controller->revoke($root->getId(), $uid('D'), $blocked['fingerprint'])->getStatus() === 422, 'Blocked plan executes no changes');
    check(isset($manager->getAccessList($sub1, true, true)['users'][$uid('G')]), 'Blocked plan preserves other group members');
    $plan = $controller->preview($root->getId(), $uid('D'), true)->getData();
    check($plan['canExecute'] && count($plan['collateral']) === 2, 'Explicit opt-in previews group and link collateral');
    $group->removeUser($people['G']);
    check($controller->revoke($root->getId(), $uid('D'), $plan['fingerprint'], true)->getStatus() === 409, 'Changed group membership invalidates preview');
    $group->addUser($people['G']);
    $plan = $controller->preview($root->getId(), $uid('D'), true)->getData();
    check($controller->revoke($root->getId(), $uid('D'), $plan['fingerprint'], true)->getStatus() === 200, 'Confirmed collateral removes group and public-link access');
    check(!($manager->getAccessList($sub2, true, true)['public'] ?? false), 'Public link is actually revoked');
    $plan = $controller->preview($root->getId(), $uid('C'))->getData();
    check($controller->revoke($root->getId(), $uid('C'), $plan['fingerprint'])->getStatus() === 200, 'C loses top-level reshared access');
    check(isset($manager->getAccessList($sub1, true, true)['users'][$uid('E')]), 'Nextcloud promotes unrelated reshares while removing C access');
    $session->setUser($people['A']);
    $inventory = $controller->index()->getData();
    check(count($inventory['trees']) >= 1, 'Owner inventory survives Nextcloud reshare promotion');
    check($controller->destroy($cf->getFullId())->getStatus() === 200, 'Original owner can delete another user or promoted share');
    check($controller->destroy($cf->getFullId())->getStatus() === 404, 'Repeated single revocation returns 404');
    echo "COMPLETE: owner tree integration\n";
} finally {
    $session->setUser(null);
    foreach ($people as $person) $person->delete();
    $group?->delete();
}
